version: '3'
services:
  postgres1:
    image: postgres:14.5
    container_name: 1_Aslanyan_216
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./db/scripts/db1:/docker-entrypoint-initdb.d
      - ./db/config/db1:/postgresql.conf

  postgres2:
    image: postgres:14.5
    container_name: 2_Aslanyan_216
    environment:
      POSTGRES_DB: hospital
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5433"
    volumes:
      - ./db/scripts/db2:/docker-entrypoint-initdb.d
      - ./db/config/db2:/postgresql.conf

  postgres3:
    image: postgres:14.5
    container_name: 3_Aslanyan_216
    environment:
      POSTGRES_DB: trains
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5434"
    volumes:
      - ./db/scripts/db3:/docker-entrypoint-initdb.d
      - ./db/config/db3:/postgresql.conf